Numpy:

Numpy Stands for Numerical Python


Numpy is a liabrary in python which is used to deal with the arrays,it has various functions to work in domain of fourier transform,matrices and linear algebra



WHY USE NUMPY?

In pytho n we have lists to serve the purpose of array but they are very slow hence the numpy a8ims at prov9iding the array object that is  50X faster than the lists

it have various functions that make working with the arrays easier

arrays are frequently used in the data science where the speed and resources play a very important role

NOTE: Data science is branch of computer science where we study how to store ,use  and analyze the data to extract the useful information from it

WHY ARE ARRAYS FASTER THAN THE LISTS IN PYTHON?

numpy arrays are stored at the contagious locations in the memory unlike the lists hence accessing and manipulating it can be done in much more efficienbt way this behaviour is called as
locality of the reference in the python.

The Numpy are also optimized gto work with the latest cpu software

NOTE: Numpy liabrary is partially written in python  but most of the part that require fast computation are written in the c and c++


In [1]:
# Installlation of numpy 
'''pip install numpy'''
# if this command fails use python distribution that has the numpy already installed in it like anaconda and spyder


'pip install numpy'

In [2]:
# To know the vesion of the numpy currently in your pc
import numpy as np
print(np.__version__)

1.21.5


In [6]:
# Creating a numpy array
my_array=np.array([1,2,3,5])
print(my_array)
print(type(my_array))
# The numpy array is called as nd array

[1 2 3 5]
<class 'numpy.ndarray'>


Dimensions in an array
0 d arrays or scalars are the elments in a an array each value in array is a 0 d array



In [11]:
# 0d array with an element 42 in it
zeroD_array=np.array(42)
print(zeroD_array)

42


An array with 0 dimensional array as its elements is called as the one dimensional array it is themost widely used array and most basic one

In [12]:
# creating the one dimensional array
my_array=np.array([1,2,3,4,5,6])
print(my_array)

[1 2 3 4 5 6]


2 D arrays are the arrays having the one d array as its elements

These are often use to represent the matrix and  numpy has the sub module dedicated to the matrix operations named numpy.mat

In [15]:
# Creating the 2D array   

array_1=np.array([[2,3,4],[5,6,7]])
print(array_1)

[[2 3 4]
 [5 6 7]]


3D array in numpy are the arrays that have two Dimensional array as its elements


In [20]:
# creating a 3 D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [26]:
# How to check the dimensions of an array
print(array_1.ndim)
print(arr.ndim)

2
3


In [30]:
# Higher dimensional array

arr1=np.array([1,2,3,4],ndmin=5)
arr1

array([[[[[1, 2, 3, 4]]]]])

accessing the elements from an array is same as in others languages such as c ,c++ etc 

The elements of an array in numpy can be accessed through an indexing array indexing starts from them 0 in numpy 

In [31]:
# Accessing an element in the one dimensional array
array1=np.array([1,3,4,5,6])
print(array1[0])


1


In [32]:
# Accesing an element from 2 d array
array2=([ [1,2,3,4],[3,4,5,6] ])
print(array2[0][2])

3


In [34]:
# accesing an element from three dimensional array
array3=([ [ [1,2,3,4] ,[5,6,7,8,9,10] ] , [ [10,2,20,4] ,[100,68,90] ] ])
print(array3[0][0][3])

4


In [36]:
# negative indexing in a numpy array
# negative indexing starts from -1
print(array2[-1][-2])

5


Slicing the elements of an array

Slicing means extracting the elements from a specifief index

syntax for slicing out the elements from an array

arrayname[start:end:step]
    
    or
     
arrayname[start:end]


In [37]:
print(array1[0:3])

[1 3 4]


In [43]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [44]:
# Slicing with  start end and step

print(array1[0:4:2])

[1 4]


Datatypes in python
 python have following datatypes:
 
 1)String
 2)integer 
 3)float
 4)boolen
 5)complex
 
Numpy is the python liabrary that have certain more datatypes which are reffered using a single character such as i for integer

data types in numpy are as follows:

1) i-integer
2) u-unsigned integer
3) f- float
4) b-boolean
5) U -unicode string
6) M-dataetime
7) m-daltatime
8) c- complex float
9) v-fixed chunkof memory for other (void)
10) s- string


In [42]:
# Checking the data type of an array
import numpy as np
array=np.array([[1,2,3,4],[1,3,4,5]])
print(array.dtype)
array.shape


int32


(2, 4)

In [5]:
array4=np.array(['lion','tiger','zebra'])
print(array4.dtype)

<U5


In [6]:
# we can also specify the data type of the array  while  creating it

array5=np.array([1,2,4,3],dtype='S')
print(array5.dtype)

|S1


In [9]:
# Typecasting of the numpy array
# numpy array can typecasted
#example
array1=np.array([1,2,3,4])
narray1=array.astype(bool)
print(narray1)
print(narray1.dtype)

[ True  True  True  True]
bool


view and copy

The difference between the view and thw copy is that the copy is a new array while the view is the original view of an array

copy owns the data while the view doesnot own the  data

Any hanges made in the copy would not change the original array 

Any changes  made in view would change original array
 

In [18]:
# Creating the view and copy of the original array

array1=np.array([1,2,3,4])
x=array1.copy()
x[0]=8 # made changes to the copy
print(array1)
print(x)

[1 2 3 4]
[8 2 3 4]


here it can be seen that changes made to the copy did not reflected in the original aaray

In [20]:
# creating a view 
y=array1.view()
y[1]=8
print(array1)
print(y)
      

[1 8 3 4]
[1 8 3 4]


here it can be seen the changes made  to view of an original array reflect in the original array

In [26]:
# how to check that a particular thing owns the data
#to check whether the particular thing owns the data we use base function an if the base rfeturns the none then it owns the data
print(array1.base)
print(y.base)# when it doesnot own the data it returns the array itself

None
[1 8 3 4]


 The shape of a numpy array is the number of elements in each dimensions
 
 
 

In [28]:
 array1.shape # The array has an attribute shape that returns the tuple with each index having number of corresponding element

(4,)

In [34]:
# trying it for  2 dimensional array
array2=np.array([ [1,2,] ,[5,6,7] ],dtype=object)
array2.shape

(2,)

Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:




In [38]:
array1=np.array([1,2,3,4],ndmin=5)
print(array1.shape)

(1, 1, 1, 1, 4)


1) Reshaping : reshaping means changing the shape of an array
2) shape : The shape of an array is the number of elements present in each dimension
3) By changing the shape of an array  we change the dimensions of an array an number of eelements present in an array




array=np.array([1,2,3,4,5,6,7,8])
newarray=array.reshape(4,2)
print(newarray)
# this converts the array of 8 elements into  the two dimensinal array of the 2 elements each

In [50]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narray=array.reshape(2,3,2)
# conversion of 1D array to 3D array

Here the 1Darray is converted into 2 arrays containing  3 arrays each with two elemnts

In [51]:
print(narray)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [52]:
# whether the reshape arrays owns the data or not
print(narray.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


the reshaped array doesnot owns the data as it written an array


UNKNOWN DIMENSIONS
1) you allowed to have one unknown dimension while reshaping
2) Meaning that you donot have to specify the exact number for one of the dimensions\
3) you can directly pass -1   the numpy will calculate the dimension for you


In [56]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narray=narray.reshape(2,3,-1)
narray

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [57]:
# flattening an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1) # flatening means converting multidimensional array into 1D array



array([1, 2, 3, 4, 5, 6])

1) iterarting over an array
2) iterating means going through each and every element of an array one by one 
3) in multidimensional array it can be done through the using basic for loop

In [67]:
# iterating through an !D array
arr1=np.array([1,2,3,4,5])
for i in arr1:
    print(i)


1
2
3
4
5


In [68]:
# iterating through the 2D array
arr2=np.array([ [2,4,6],[5,8,9] ])
for x in arr2:
    print(x)

[2 4 6]
[5 8 9]


In [73]:
# iterating over a scalar in 2D array
for i in arr2:
    for j in i:
        print(j)
# this is the code that was used gto iterate over a scalar

2
4
6
5
8
9


In [72]:
# iterating over the 3D array
# creating a 3D array
arr3=np.array([ [ [1,2,3] ,[2,4,5] ],[ [12,1,3],[15,16,17] ] ])
print(arr3)
for i in arr3:
    for j in i:
        for k in j:
            print(k)


[[[ 1  2  3]
  [ 2  4  5]]

 [[12  1  3]
  [15 16 17]]]
1
2
3
2
4
5
12
1
3
15
16
17


1) An alternate way to iterate over the array is a "nditer()" of the numpy array called as nd array it can be used for a basic iterations to advanced iteration
 
2) Basic for loop can also be used for iterating through the elements of an array but as the dimensions increases the number of for loop also increases  hence it makes the task complicated hence the nditerfunction is used 




In [74]:
for x in np.nditer(arr3):
    print(x)

1
2
3
2
4
5
12
1
3
15
16
17


1) the datatype of the scalar can be changed while iterating through it
2) this can done by passing the attibute called op_dtypes in the function nd iter
3) it doesnot change the data type of the scalar as in place but it changes it in another place hence we have to pass a buffer as flag


In [79]:
for x in np.nditer(arr3,flags=['buffered'],op_dtypes='S'):
    print(x)

b'1'
b'2'
b'3'
b'2'
b'4'
b'5'
b'12'
b'1'
b'3'
b'15'
b'16'
b'17'


In [80]:
for x in np.nditer(arr2[:, ::2]):
  print(x)

2
6
5
9


1) joins :
    as we use key to join two tables in sql we use the axes to join two arrays in numpy
2) the function that we use to join the arrays is concatebate functions in this functions we pass arrays to be joined together and pass axes as 0 or 1
   and if dont pass it explicitly it takes it as default 0
   

In [100]:
array1=np.array([1,2,3,4])
array2=np.array([3,4,5,6])
arrr=np.concatenate((array1,array2),axis=0)
arrr

array([1, 2, 3, 4, 3, 4, 5, 6])

In [97]:
array3=np.array([ [1,2,3,4],[3,4,5,6] ])
array4=np.array([ [11,12,13,14],[13,14,15,16] ])

#arrrr=np.concatenate((array2,array3),axis=1)
#arrrr
arrrr=np.concatenate((array2,array3),axis=1)
arrrr

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [3, 4, 5, 6, 3, 4, 5, 6]])

In [101]:
arrr=np.stack((array1,array2))
arrr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [102]:
arrr=np.stack((array1,array2),axis=1)
arrr

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

In [103]:
# sdatacking aliong rows
arrr=np.hstack((array1,array2))
arrr

array([1, 2, 3, 4, 3, 4, 5, 6])

In [105]:
# Stacking along columns
arrr=np.vstack((array1,array2))
arrr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [106]:
# stacking along depth
arrr=np.dstack((array1,array2))
arrr

array([[[1, 3],
        [2, 4],
        [3, 5],
        [4, 6]]])

1) Splitting an array is exactly the reverse process of the  joining an array
2) in joining an array multiple arrays are converted as the one aaray in spliting an array one array is split into various arrays
3) we use array_ split function to split an aaray and pass the array and the number of splits we want to carry

In [109]:
np.array_split(arr3,8)# splitting of  3d array

[array([[[1, 2, 3],
         [2, 4, 5]]]),
 array([[[12,  1,  3],
         [15, 16, 17]]]),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32)]

In [110]:
np.array_split(arr2,8) # splitting of 2D array

[array([[2, 4, 6]]),
 array([[5, 8, 9]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [111]:
np.array_split(arr1,8) # Splitting of 1D array

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

1) As there were three functions in join vertical join ,horizontal join ,depth join 
2) smilarly split have three split functions



In [121]:
ARR1 = np.hsplit(arr2, 3)# horizontal split
ARR1

[array([[2],
        [5]]),
 array([[4],
        [8]]),
 array([[6],
        [9]])]

In [126]:
np.vsplit(arr2, 2)# vertical split

[array([[2, 4, 6]]), array([[5, 8, 9]])]

In [134]:
np.dsplit(arr3,1) # 'split by depth 
# Note Dsplit works for the 3 or more than three dimensional array only

[array([[[ 1,  2,  3],
         [ 2,  4,  5]],
 
        [[12,  1,  3],
         [15, 16, 17]]])]

1) in numpy we can search for an element in an array using the function where()
2) where functions written the index of the element found in the aaray

In [135]:
arr1

array([1, 2, 3, 4, 5])

In [143]:
print(np.where(arr1==4))

(array([3], dtype=int64),)


In [145]:
print(np.where(arr1==6)) # when element is not present in an array

(array([], dtype=int64),)


In [149]:
# find the indices whwre the values are even
print(np.where(arr1%2==0))
# here it returns the idices 1 and  3  where there are the  even numbers

(array([1, 3], dtype=int64),)


In [152]:
#find the ndices where values are odd
print(np.where(arr1%2!=0))

(array([0, 2, 4], dtype=int64),)


1) Searchsorted() function  is the another function which performs the binary search in an array and returns the index at which the element is present
2) search sorted function is used for sorted array
3) syntax searchsorted(arrayname,elementtobesearched,side='right'/'left'), here the function would search for an element from either right side or the left side

In [156]:
print(np.searchsorted(arr1,1,side='right'))
# The method starts the search from the right and returns the first index where the number 4 is no longer larger than the next value.

1


In [160]:
# to search various elements at a time we can pass list of elements to be searched to searchsorted()
print(np.searchsorted(arr1,[-1,2,7],side='left'))

[0 1 5]


1) Sorting: converting a sequence int an ordered sequence is called as the sorting
2) ordered sequence: The ordered sequence is the sequence where the elemnts are srranged in "numerical" or "alphabetical" order decending or ascending
3) To sort the numpy array we can use function sort()

In [162]:
print(np.sort(arr1)) # sorting the one dimensional array

[1 2 3 4 5]


In [164]:
#sorting 2 dimensional array
print(np.sort(arr2))

[[2 4 6]
 [5 8 9]]


1) Filtering an array : getting the some elements from an array and creating a new array is called filtering
2) for filtering we can use boolean index list
3) Following are the ways for creating filtered arrays

In [170]:
# 1)  Using boolean index list list

x=[True,True,True,False,False]
narr1=arr1[x]
print(narr1)
print(arr1)

[1 2 3]
[1 2 3 4 5]
